import type { LucideIcon } from "lucide-react";
import {
  Activity, ArrowDown, ArrowRight, Box, Boxes, Braces, Cable, Check, CircleDot,
  CircleX, Clock3, Cloud, Container, Cpu, Database, FileClock, Gauge, GitBranch,
  Globe2, HardDrive, Layers3, ListChecks, Lock, MemoryStick, Monitor, Network,
  Package, PlayCircle, RadioTower, RefreshCcw, Route, Router, Scale, Search,
  Server, Shield, ShieldCheck, Split, Timer, TriangleAlert, Unplug, UserRound,
  X, Zap,
} from "lucide-react";

export type SlideProps = { step: number };
export type SectionKey = "fundamentos" | "virtualizacao" | "containers" | "kubernetes" | "rede" | "replicacao" | "distribuidos" | "fechamento";
export type SlideDefinition = { title: string; duration: string; maxStep: number; section: SectionKey; component: (props: SlideProps) => React.ReactNode };

export const sections: Array<{ key: SectionKey; label: string; start: number; end: number }> = [
  { key: "fundamentos", label: "Fundamentos", start: 1, end: 6 },
  { key: "virtualizacao", label: "Virtualização", start: 7, end: 12 },
  { key: "containers", label: "Containers", start: 13, end: 19 },
  { key: "kubernetes", label: "Orquestração", start: 20, end: 31 },
  { key: "rede", label: "Rede e multi-AZ", start: 32, end: 39 },
  { key: "replicacao", label: "Replicação", start: 40, end: 48 },
  { key: "distribuidos", label: "Multi-região", start: 49, end: 55 },
  { key: "fechamento", label: "Síntese", start: 56, end: 60 },
];

const sectionLabels: Record<SectionKey, string> = {
  fundamentos: "Fundamentos", virtualizacao: "Virtualização", containers: "Containers", kubernetes: "Orquestração",
  rede: "Rede e alta disponibilidade", replicacao: "Replicação", distribuidos: "Sistemas distribuídos", fechamento: "Síntese",
};

function Reveal({ at, step, children, className = "" }: { at: number; step: number; children: React.ReactNode; className?: string }) {
  return <div className={`reveal ${step >= at ? "is-visible" : ""} ${className}`}>{children}</div>;
}

function Slide({ title, section, children, className = "" }: { number: number; title: string; section: SectionKey; children: React.ReactNode; className?: string }) {
  return <article className={`deck-slide ${className}`}><header className="slide-heading"><h1>{title}</h1></header>{children}<span className="slide-section">{sectionLabels[section]}</span></article>;
}

function Bullets({ children, compact = false }: { children: React.ReactNode; compact?: boolean }) { return <ul className={`bullet-list ${compact ? "compact" : ""}`}>{children}</ul>; }

function TextSlide({ number, title, section, bullets, visual, className = "" }: { number: number; title: string; section: SectionKey; bullets: React.ReactNode[]; visual: React.ReactNode; className?: string }) {
  return <Slide number={number} title={title} section={section} className={`text-slide ${className}`}><div className="text-with-aside"><Bullets>{bullets.map((bullet, index) => <li key={index}>{bullet}</li>)}</Bullets>{visual}</div></Slide>;
}

function DiagramSlide({ number, title, section, bullets, note, children, className = "" }: { number: number; title: string; section: SectionKey; bullets: React.ReactNode[]; note?: React.ReactNode; children: React.ReactNode; className?: string }) {
  return <Slide number={number} title={title} section={section} className={`diagram-slide ${className}`}><div className="diagram-with-context"><div className="diagram-context"><Bullets compact>{bullets.map((bullet, index) => <li key={index}>{bullet}</li>)}</Bullets>{note && <div className="definition-note">{note}</div>}</div><div className="diagram-canvas">{children}</div></div></Slide>;
}

function IconLabel({ icon: Icon, title, subtitle, tone = "green" }: { icon: LucideIcon; title: string; subtitle?: string; tone?: string }) { return <div className={`icon-label ${tone}`}><Icon/><div><b>{title}</b>{subtitle && <small>{subtitle}</small>}</div></div>; }
function FlowArrow({ label }: { label?: string }) { return <div className="flow-arrow">{label && <span>{label}</span>}<i/><ArrowRight/></div>; }

const topicMap: Array<{ key: SectionKey; label: string; description: string; icon: LucideIcon }> = [
  { key: "fundamentos", label: "Fundamentos", description: "infraestrutura física e failure domains", icon: Cloud },
  { key: "virtualizacao", label: "Virtualização", description: "VMs, hypervisor e recursos virtuais", icon: Server },
  { key: "containers", label: "Containers", description: "processos, namespaces, cgroups e imagens", icon: Container },
  { key: "kubernetes", label: "Orquestração", description: "reconciliação, scheduler e self-healing", icon: Boxes },
  { key: "rede", label: "Rede e multi-AZ", description: "endereçamento, Services e disponibilidade", icon: Network },
  { key: "replicacao", label: "Replicação", description: "WAL, lag, ACK e quorum", icon: Database },
  { key: "distribuidos", label: "Multi-região", description: "consistência, consenso, CAP e recuperação", icon: Globe2 },
  { key: "fechamento", label: "Síntese", description: "falhas, decisões e discussão", icon: ListChecks },
];

function TopicMapSlide({ current }: { current: SectionKey }) {
  const position = topicMap.findIndex((topic) => topic.key === current);
  const active = topicMap[position];
  return <article className="deck-slide topic-map-slide">
    <header className="slide-heading"><h1>Agora: {active.label}</h1></header>
    <div className="topic-map-layout">
      <div className="topic-map-intro">
        <span>{String(position + 1).padStart(2, "0")} / {String(topicMap.length).padStart(2, "0")}</span>
        <h2>{active.description}</h2>
        <p>Este mapa reaparece em cada mudança de tema para deixar explícito onde estamos e qual problema o próximo bloco resolve.</p>
      </div>
      <div className="topic-map-grid">
        {topicMap.map((topic, index) => {
          const Icon = topic.icon;
          const state = topic.key === current ? "current" : index < position ? "complete" : "upcoming";
          return <section key={topic.key} className={state}><span>{index + 1}</span><Icon/><div><b>{topic.label}</b><small>{topic.description}</small></div>{state === "current" && <em>tópico atual</em>}{state === "complete" && <Check/>}</section>;
        })}
      </div>
    </div>
    <span className="slide-section">Mapa da apresentação</span>
  </article>;
}

const TopicFundamentos = () => <TopicMapSlide current="fundamentos"/>;
const TopicVirtualizacao = () => <TopicMapSlide current="virtualizacao"/>;
const TopicContainers = () => <TopicMapSlide current="containers"/>;
const TopicKubernetes = () => <TopicMapSlide current="kubernetes"/>;
const TopicRede = () => <TopicMapSlide current="rede"/>;
const TopicReplicacao = () => <TopicMapSlide current="replicacao"/>;
const TopicDistribuidos = () => <TopicMapSlide current="distribuidos"/>;
const TopicFechamento = () => <TopicMapSlide current="fechamento"/>;

function CoverVisual() { const layers = [[Cloud,"Região / AZ","failure domains"],[Server,"VM","hardware virtualizado"],[Container,"Container","processo isolado"],[Boxes,"Kubernetes","estado reconciliado"],[Database,"Dados","replicação e consenso"]] as Array<[LucideIcon,string,string]>; return <div className="cover-visual">{layers.map(([Icon,title,detail],index)=><div key={title} className="cover-layer"><span>{index+1}</span><Icon/><b>{title}</b><small>{detail}</small></div>)}</div>; }
function Slide01() { return <Slide number={1} title="Cloud por baixo das abstrações" section="fundamentos" className="cover-slide"><div className="cover-layout"><div className="cover-copy"><p>Como uma aplicação sai de um servidor físico, escala por várias máquinas e continua correta quando máquinas, zonas ou regiões falham?</p><ul><li>Virtualização e containers explicam <b>isolamento</b>.</li><li>Kubernetes explica <b>coordenação de compute</b>.</li><li>Replicação e consenso explicam <b>sobrevivência do estado</b>.</li></ul></div><CoverVisual/></div></Slide>; }

function SingleVmVisual() { return <div className="visual-panel single-vm"><div className="client-row"><UserRound/><b>Usuários</b></div><ArrowDown/><div className="vm-shell"><header><Server/><b>VM única</b><small>um sistema operacional</small></header><div><Box/>Aplicação</div><div><Database/>Banco local</div><div><HardDrive/>Disco</div></div><div className="risk-strip"><TriangleAlert/><span>Uma falha interrompe compute e estado ao mesmo tempo.</span></div></div>; }
function Slide02() { return <TextSlide number={2} title="Começamos com uma aplicação em uma VM" section="fundamentos" bullets={[<>Uma VM com aplicação e banco é suficiente para publicar um primeiro sistema. O modelo é simples porque <strong>compute, rede e estado</strong> compartilham o mesmo ciclo de vida.</>,<>A simplicidade também concentra o risco: manutenção do host, falha de disco ou kernel panic removem todos os componentes ao mesmo tempo. Reiniciar a VM recupera o serviço apenas se o estado ainda estiver íntegro.</>,<>A evolução da arquitetura será guiada por uma pergunta concreta: <strong>qual componente deve continuar funcionando após qual falha?</strong></>]} visual={<SingleVmVisual/>}/>; }

function SharedCloudVisual() { return <div className="visual-panel shared-cloud"><header><Cloud/><div><b>Pool físico do provedor</b><small>capacidade compartilhada, alocada sob demanda</small></div></header><div className="rack-grid">{["Host 01","Host 02","Host 03"].map((h,i)=><section key={h}><Server/><b>{h}</b><span><i style={{width:`${[72,48,84][i]}%`}}/>CPU</span><span><i style={{width:`${[56,70,43][i]}%`}}/>RAM</span><small>{i===1?"VM da aplicação":"outras cargas"}</small></section>)}</div><div className="allocation-note"><Gauge/><span>A API escolhe capacidade; ela não elimina os limites do hardware.</span></div></div>; }
function Slide03() { return <TextSlide number={3} title="Cloud é infraestrutura compartilhada" section="fundamentos" bullets={[<>Uma região cloud continua sendo composta por prédios, energia, racks, servidores, discos e switches. A diferença é que software controla a alocação desses recursos e expõe uma <strong>API de infraestrutura</strong>.</>,<>O provedor agrupa capacidade física e a divide entre clientes com virtualização, redes virtuais e storage distribuído. Elasticidade significa realocar recursos desse pool; não significa capacidade infinita.</>,<>Cada abstração esconde detalhes operacionais, mas mantém propriedades físicas: CPUs são escalonadas, pacotes atravessam enlaces e gravações precisam chegar a algum meio durável.</>]} visual={<SharedCloudVisual/>}/>; }

function FailureDomainsVisual() { const rows=[[Server,"Processo / VM","reinício local"],[HardDrive,"Host / disco","outra máquina"],[Network,"Rack / switch","outro rack"],[Cloud,"Zona de disponibilidade","outra AZ"],[Globe2,"Região","outra região"]] as Array<[LucideIcon,string,string]>; return <div className="visual-panel failure-domains"><header><Shield/><b>Escopo da falha → escopo da redundância</b></header>{rows.map(([Icon,name,response],i)=><div key={name}><span>{i+1}</span><Icon/><b>{name}</b><ArrowRight/><small>{response}</small></div>)}</div>; }
function Slide04() { return <TextSlide number={4} title="Falhas possuem escopos diferentes" section="fundamentos" bullets={[<>Um processo pode morrer enquanto o host permanece saudável; um host pode falhar sem afetar o rack; uma zona pode perder conectividade sem derrubar a região inteira. Esses escopos são chamados de <strong>failure domains</strong>.</>,<>Redundância só funciona quando as cópias não compartilham a falha que deveriam tolerar. Duas VMs no mesmo host protegem contra processo, mas não contra a perda daquele host.</>,<>Alta disponibilidade começa pela definição da falha-alvo. A arquitetura, o custo e a latência mudam quando o requisito passa de host para AZ ou de AZ para região.</>]} visual={<FailureDomainsVisual/>}/>; }

function RoadmapVisual() { const items=[[Cpu,"Isolar hardware"],[Container,"Empacotar processos"],[Boxes,"Coordenar compute"],[Network,"Conectar endpoints"],[Database,"Replicar estado"]] as Array<[LucideIcon,string]>; return <div className="roadmap-visual">{items.map(([Icon,label],i)=><div key={label}><span>{i+1}</span><Icon/><b>{label}</b>{i<items.length-1&&<ArrowDown/>}</div>)}</div>; }
function Slide05() { return <Slide number={5} title="A arquitetura será construída em cinco etapas" section="fundamentos" className="roadmap-slide"><div className="roadmap-layout"><div><Bullets><li>Virtualização transforma servidores físicos em unidades de infraestrutura isoladas.</li><li>Containers transformam ambientes de aplicação em processos reproduzíveis.</li><li>Orquestração mantém o compute próximo do estado desejado.</li><li>Rede preserva descoberta e roteamento apesar de endpoints efêmeros.</li><li>Replicação preserva o estado quando compute ou localidades falham.</li></Bullets></div><RoadmapVisual/></div></Slide>; }

function UtilizationVisual() { return <div className="visual-panel utilization"><section><h3>Um serviço por servidor</h3>{["Serviço A","Serviço B","Serviço C"].map((s,i)=><div key={s}><Server/><b>{s}</b><span><i style={{width:`${[24,31,18][i]}%`}}/></span><small>capacidade ociosa</small></div>)}</section><ArrowRight/><section className="pooled"><h3>Hosts virtualizados</h3><div className="pool-bar"><i/><i/><i/></div><div className="vm-chips"><span>VM A</span><span>VM B</span><span>VM C</span><span>livre</span></div><p>Consolidação sem misturar kernels convidados.</p></section></div>; }
function Slide06() { return <TextSlide number={6} title="Virtualização melhora utilização e isolamento" section="virtualizacao" bullets={[<>Antes da virtualização, era comum dedicar um servidor a cada aplicação para evitar conflitos. Isso simplificava isolamento, mas deixava CPU e memória ociosas e tornava provisionamento lento.</>,<>O hypervisor permite executar várias máquinas virtuais no mesmo host, cada uma com kernel, memória e dispositivos virtuais próprios. O provedor pode consolidar cargas e mover a fronteira de isolamento para software.</>,<>A VM vira a unidade contratada pelo cliente, mas continua consumindo recursos físicos compartilhados. O isolamento é forte; a capacidade e o desempenho ainda dependem do host.</>]} visual={<UtilizationVisual/>}/>; }

function HypervisorVisual() { return <div className="visual-panel hypervisor-stack"><div className="vm-row">{["VM A","VM B","VM C"].map((v,i)=><section key={v}><Monitor/><b>{v}</b><span>Guest OS</span><small>{["2 vCPU · 4 GiB","4 vCPU · 8 GiB","1 vCPU · 2 GiB"][i]}</small></section>)}</div><div className="hypervisor-bar"><Braces/><b>Hypervisor</b><span>vCPU · memória · dispositivos</span></div><div className="host-hardware"><Cpu/><MemoryStick/><HardDrive/><Network/><b>Hardware físico</b></div></div>; }
function Slide07() { return <TextSlide number={7} title="O hypervisor apresenta hardware virtual" section="virtualizacao" bullets={[<>Em um hypervisor bare-metal, o monitor de máquinas virtuais controla diretamente o hardware e expõe a cada guest uma plataforma virtual: vCPUs, memória, controladores de disco e interfaces de rede.</>,<>O guest executa seu próprio kernel e acredita controlar a máquina. Operações privilegiadas são interceptadas ou aceleradas por extensões como Intel VT-x e AMD-V, mantendo o controle no hypervisor.</>,<>KVM, Xen, Hyper-V e ESXi implementam arquiteturas diferentes, mas resolvem o mesmo contrato: <strong>múltiplos sistemas operacionais isolados sobre um conjunto físico finito</strong>.</>]} visual={<HypervisorVisual/>}/>; }

function CpuScheduleVisual({step}:{step:number}) { return <div className="cpu-schedule"><div className="vcpu-list">{["VM A · vCPU 0","VM A · vCPU 1","VM B · vCPU 0","VM C · vCPU 0"].map((v,i)=><Reveal key={v} at={i>1?1:0} step={step}><span><Cpu/>{v}</span></Reveal>)}</div><FlowArrow label="scheduler do hypervisor"/><div className="core-row">{[0,1,2,3].map(c=><Reveal key={c} at={c>1?2:0} step={step}><span><CircleDot/><b>Core {c}</b><small>timeslices</small></span></Reveal>)}</div><Reveal at={2} step={step} className="cpu-warning"><Timer/><span>Overcommit aumenta utilização, mas produz contenção e steal time.</span></Reveal></div>; }
function Slide08({step}:SlideProps) { return <DiagramSlide number={8} title="vCPUs são escalonadas sobre cores físicos" section="virtualizacao" bullets={[<>Uma vCPU não é um core reservado por definição. Ela é uma entidade escalonável que recebe tempo em um core físico quando o hypervisor a seleciona.</>,<>Se houver mais vCPUs prontas que cores disponíveis, VMs competem por tempo de CPU. O guest observa atraso sem controlar a causa externa.</>]} note={<><b>Consequência</b><span>O tamanho nominal da VM não descreve sozinho a latência sob contenção.</span></>}><CpuScheduleVisual step={step}/></DiagramSlide>; }

function MemoryIoVisual() { return <div className="memory-io"><section><header><MemoryStick/><b>Memória</b></header><div className="address-chain"><span>virtual do processo</span><ArrowRight/><span>física do guest</span><ArrowRight/><span>física do host</span></div><p>Nested page tables aceleram duas traduções de endereço.</p></section><section><header><HardDrive/><b>I/O</b></header><div className="device-path"><span>driver guest</span><ArrowRight/><span>dispositivo virtual</span><ArrowRight/><span>driver host / hardware</span></div><p>Emulação maximiza compatibilidade; paravirtualização reduz overhead.</p></section><section className="shared-note"><Zap/><span>CPU, memória e I/O possuem caminhos diferentes; “overhead da VM” não é um único número.</span></section></div>; }
function Slide09() { return <TextSlide number={9} title="Memória e I/O exigem outras traduções" section="virtualizacao" bullets={[<>Para memória, o endereço virtual do processo é traduzido para um endereço físico do guest e depois para memória física do host. Hardware moderno mantém estruturas como EPT/NPT para reduzir o custo desse segundo nível.</>,<>Para I/O, o guest pode usar dispositivos emulados ou drivers paravirtualizados, como virtio. Emulação favorece compatibilidade; paravirtualização reduz trocas de contexto e cópias.</>,<>O desempenho depende da carga: CPU-bound, memória aleatória, rede de pacotes pequenos e storage síncrono pressionam partes diferentes do caminho virtualizado.</>]} visual={<MemoryIoVisual/>}/>; }

function VmContainerCompare() { return <div className="visual-panel vm-container-compare"><section><header><Server/><b>Máquinas virtuais</b></header><div className="stack"><span>App</span><span>Guest libraries</span><span className="kernel">Guest kernel</span><span>Hypervisor</span></div><p>Fronteira inclui um kernel completo.</p></section><section><header><Container/><b>Containers</b></header><div className="stack"><span>App</span><span>Libraries</span><span className="kernel">Kernel compartilhado</span><span>Runtime</span></div><p>Fronteira isola processos no mesmo kernel.</p></section></div>; }
function Slide10() { return <TextSlide number={10} title="VMs e containers isolam em níveis diferentes" section="virtualizacao" bullets={[<>A VM isola uma máquina inteira e permite kernels distintos no mesmo host. Isso cria uma fronteira robusta, mas aumenta tempo de inicialização, consumo de memória e trabalho de atualização do sistema convidado.</>,<>Muitas aplicações não precisam de outro kernel; precisam apenas de dependências reproduzíveis e isolamento entre processos. Containers exploram essa oportunidade usando mecanismos do kernel do host.</>,<>Por isso, containers frequentemente executam <strong>dentro de VMs</strong> na cloud: a VM mantém a fronteira de tenant e o container fornece densidade e portabilidade para a aplicação.</>]} visual={<VmContainerCompare/>}/>; }

function ProcessIsolationVisual() { return <div className="visual-panel process-isolation"><header><Container/><div><b>Container web</b><small>um conjunto de processos Linux</small></div></header><div className="process-table"><span><b>Dentro</b><code>PID 1</code><small>/app/server</small></span><ArrowRight/><span><b>No host</b><code>PID 18473</code><small>mesmo processo</small></span></div><div className="kernel-share"><Cpu/><MemoryStick/><Network/><b>Kernel do host compartilhado</b></div><p>O isolamento muda o que o processo enxerga e quanto pode consumir.</p></div>; }
function Slide11() { return <TextSlide number={11} title="Container é um processo isolado" section="containers" bullets={[<>Um container não inicializa uma máquina: o runtime cria processos comuns do sistema operacional com uma visão controlada do ambiente. Dentro do namespace, o processo pode aparecer como PID 1; no host, possui outro PID.</>,<>Todos os containers Linux no mesmo host compartilham o kernel. Bibliotecas e filesystem podem ser diferentes, mas syscalls terminam na mesma implementação do kernel.</>,<>A inicialização é rápida porque não há boot de guest OS. A contrapartida é que uma falha ou vulnerabilidade no kernel compartilhado afeta uma fronteira maior.</>]} visual={<ProcessIsolationVisual/>}/>; }

function NamespaceVisual() { const data=[["PID","processos e árvore de PIDs"],["NET","interfaces, rotas e portas"],["MNT","mount points e root filesystem"],["USER","UIDs e capabilities"],["UTS","hostname"],["IPC","memória compartilhada e filas"]]; return <div className="visual-panel namespaces"><header><Search/><b>O que o processo consegue enxergar?</b></header><div>{data.map(([name,desc])=><section key={name}><code>{name}</code><span>{desc}</span></section>)}</div><p>Namespaces não limitam consumo; eles recortam a visão dos recursos.</p></div>; }
function Slide12() { return <TextSlide number={12} title="Namespaces mudam a visão do processo" section="containers" bullets={[<>Namespaces particionam recursos globais do kernel. Um PID namespace fornece uma árvore de processos própria; um network namespace fornece interfaces, rotas e tabela de portas independentes.</>,<>Mount, UTS, IPC e user namespaces isolam filesystem, hostname, comunicação entre processos e identidades. A combinação forma a “máquina aparente” vista pelo processo.</>,<>Isolamento não significa segurança automática. Capabilities, seccomp, AppArmor/SELinux, filesystem somente leitura e user namespaces reduzem o poder disponível se o processo for comprometido.</>]} visual={<NamespaceVisual/>}/>; }

function CgroupVisual() { return <div className="visual-panel cgroups"><header><Gauge/><b>cgroup v2 · orçamento por grupo</b></header><section><Cpu/><div><b>CPU</b><span><i style={{width:"62%"}}/></span><small>peso e quota</small></div></section><section><MemoryStick/><div><b>Memória</b><span><i style={{width:"83%"}}/></span><small>high, max e OOM</small></div></section><section><HardDrive/><div><b>I/O</b><span><i style={{width:"41%"}}/></span><small>peso e limites</small></div></section><p><ShieldCheck/>Hierarquia permite contabilizar e controlar descendentes como uma unidade.</p></div>; }
function Slide13() { return <TextSlide number={13} title="cgroups controlam consumo de recursos" section="containers" bullets={[<>Namespaces respondem “o que o processo vê”; control groups respondem <strong>“quanto o grupo pode consumir”</strong>. O kernel contabiliza CPU, memória e I/O para uma hierarquia de processos.</>,<>CPU pode ser compartilhada por peso ou limitada por quota. Memória possui limiares de pressão e limite máximo; ao excedê-lo, o kernel pode selecionar processos do cgroup para OOM kill.</>,<>Esses mecanismos são a base dos requests e limits de plataformas superiores. O orquestrador escolhe valores; o kernel efetivamente mede, restringe e reporta o consumo.</>]} visual={<CgroupVisual/>}/>; }

function ImageLayersVisual() { const layers=[["sha:a91","App e configuração"],["sha:2bd","Dependências"],["sha:80f","Runtime da linguagem"],["sha:31e","Base mínima"]]; return <div className="visual-panel image-layers"><header><Layers3/><b>Imagem OCI</b><small>manifesto + config + layers</small></header><div className="layer-stack">{layers.map(([sha,label],i)=><section key={sha} style={{marginLeft:`${i*.55}cqw`}}><code>{sha}</code><b>{label}</b><Lock/></section>)}</div><div className="cow-layer"><FileClock/><b>Camada gravável do container</b><span>copy-on-write durante a execução</span></div></div>; }
function Slide14() { return <TextSlide number={14} title="Imagens são camadas imutáveis" section="containers" bullets={[<>Uma imagem OCI descreve configuração e uma sequência ordenada de filesystem layers. Cada layer é endereçada por conteúdo, permitindo cache e compartilhamento entre imagens.</>,<>Ao iniciar o container, o runtime combina as camadas somente leitura e adiciona uma camada gravável com copy-on-write. Alterar um arquivo não modifica a imagem original.</>,<>A imagem torna a execução reproduzível, mas não preserva dados mutáveis. Estado durável deve sair da camada efêmera para volumes ou serviços de dados.</>]} visual={<ImageLayersVisual/>}/>; }

function RuntimeChainVisual() { const items=[[PlayCircle,"CLI / API","solicita execução"],[Boxes,"containerd ou CRI-O","gerencia imagens e lifecycle"],[Package,"runc / crun","aplica o bundle OCI"],[Braces,"Kernel Linux","namespaces + cgroups + syscalls"]] as Array<[LucideIcon,string,string]>; return <div className="visual-panel runtime-chain">{items.map(([Icon,title,detail],i)=><section key={title}><Icon/><div><b>{title}</b><small>{detail}</small></div>{i<items.length-1&&<ArrowDown/>}</section>)}</div>; }
function Slide15() { return <TextSlide number={15} title="O runtime converte a imagem em processos" section="containers" bullets={[<>Ferramentas como Docker oferecem build, distribuição e experiência de desenvolvimento. Em produção, um runtime de alto nível como containerd ou CRI-O gerencia imagens e chama um runtime OCI de baixo nível.</>,<>runc ou equivalente recebe o bundle, configura namespaces, cgroups, mounts, capabilities e inicia o processo definido na imagem. Depois disso, o processo é supervisionado como qualquer outro.</>,<>Essa separação explica por que Kubernetes não precisa do Docker Engine: ele integra-se a runtimes por uma interface própria e depende dos padrões OCI para imagem e execução.</>]} visual={<RuntimeChainVisual/>}/>; }

function OneHostVisual() { return <div className="visual-panel one-host"><div className="host-box"><header><Server/><b>Host 01</b></header><div>{["web-1","web-2","worker-1","api-1"].map(x=><span key={x}><Container/>{x}</span>)}</div><CircleX/></div><div className="host-consequence"><Unplug/><b>Se o host falhar…</b><span>todos os processos param juntos; nenhum mecanismo local escolhe outro host.</span></div></div>; }
function Slide16() { return <TextSlide number={16} title="Um host não é uma plataforma" section="containers" bullets={[<>Containers resolvem empacotamento e isolamento dentro de uma máquina. Eles não escolhem em qual máquina executar, não substituem réplicas perdidas e não criam um endpoint estável quando o processo muda de IP.</>,<>Em dezenas de hosts, decisões manuais tornam-se inconsistentes: capacidade é desperdiçada, versões divergem e falhas exigem intervenção rápida de operadores.</>,<>O próximo problema não é “como iniciar um container”, mas <strong>como manter milhares de processos convergindo para uma intenção declarada apesar de mudanças e falhas</strong>.</>]} visual={<OneHostVisual/>}/>; }

function OrchestrationVisual() { const items=[[Scale,"Placement","escolher um Node"],[RefreshCcw,"Reconciliação","repor réplicas"],[Network,"Descoberta","estabilizar endpoints"],[Activity,"Saúde","retirar instâncias ruins"],[GitBranch,"Rollout","mudar versão gradualmente"],[Gauge,"Escala","ajustar capacidade"]] as Array<[LucideIcon,string,string]>; return <div className="visual-panel orchestration-grid">{items.map(([Icon,title,detail])=><section key={title}><Icon/><b>{title}</b><small>{detail}</small></section>)}</div>; }
function Slide17() { return <TextSlide number={17} title="Orquestração coordena um conjunto de hosts" section="kubernetes" bullets={[<>Um orquestrador recebe uma descrição da aplicação e transforma capacidade dispersa em uma plataforma: escolhe Nodes, inicia workloads, monitora saúde e substitui instâncias perdidas.</>,<>O valor não está em executar `docker run` remotamente. Está em manter invariantes — quantidade de réplicas, versão, recursos e distribuição — mesmo quando o ambiente muda.</>,<>Kubernetes é o exemplo central porque expõe esses mecanismos de forma explícita: API declarativa, control loops, scheduler, objetos de rede e extensões.</>]} visual={<OrchestrationVisual/>}/>; }

function ReconciliationVisual({step}:{step:number}) { return <div className="reconciliation"><section className="desired"><ListChecks/><b>Estado desejado</b><code>replicas: 3</code></section><FlowArrow label="observar"/><section className="observed"><Search/><b>Estado observado</b><div className="pod-icons"><span/><span/>{step<1?<i/>:<span/>}</div><small>{step<1?"2 Pods saudáveis":"3 Pods saudáveis"}</small></section><Reveal at={1} step={step} className="reconcile-action"><RefreshCcw/><b>diferença detectada</b><span>controller cria um novo Pod</span></Reveal><Reveal at={2} step={step} className="reconcile-loop"><Check/><b>convergência</b><span>observado = desejado</span></Reveal></div>; }
function Slide18({step}:SlideProps) { return <DiagramSlide number={18} title="Kubernetes reconcilia estado desejado" section="kubernetes" bullets={[<>O manifesto declara o resultado, não uma sequência de comandos. Controllers observam a API e executam ações para reduzir a diferença entre estado atual e desejado.</>,<>A reconciliação é contínua: depois de alcançar três réplicas, o sistema continua observando. Se um Pod desaparecer, a mesma regra volta a produzir uma ação.</>]} note={<><b>Modelo mental</b><span>Kubernetes é um conjunto de control loops cooperando por meio de uma API.</span></>}><ReconciliationVisual step={step}/></DiagramSlide>; }

function ObjectChainVisual() { const items=[[Braces,"Deployment","versão e estratégia"],[Boxes,"ReplicaSet","quantidade de Pods"],[Container,"Pod","unidade agendada"],[Server,"Node","capacidade escolhida"]] as Array<[LucideIcon,string,string]>; return <div className="visual-panel object-chain">{items.map(([Icon,title,detail],i)=><section key={title}><Icon/><div><b>{title}</b><small>{detail}</small></div>{i<items.length-1&&<ArrowDown/>}</section>)}</div>; }
function Slide19() { return <TextSlide number={19} title="Objetos formam uma cadeia de controle" section="kubernetes" bullets={[<>Um Deployment não executa containers diretamente. Seu controller cria ou ajusta ReplicaSets; o ReplicaSet cria Pods; o scheduler associa Pods pendentes a Nodes.</>,<>Cada objeto possui `spec` para intenção e `status` para observação. Componentes diferentes assumem responsabilidade por partes pequenas do sistema.</>,<>A composição reduz acoplamento, mas introduz consistência eventual do control plane. Entre alterar um Deployment e todos os Pods convergirem, vários control loops precisam reagir.</>]} visual={<ObjectChainVisual/>}/>; }

function ClusterArchitecture() { return <div className="cluster-architecture"><section className="control-plane"><header><Cloud/><b>Control plane</b></header><div><IconLabel icon={Braces} title="API Server" subtitle="fronteira da API"/><IconLabel icon={Database} title="etcd" subtitle="estado persistente"/><IconLabel icon={Scale} title="Scheduler" subtitle="placement"/><IconLabel icon={RefreshCcw} title="Controllers" subtitle="reconciliação"/></div></section><div className="api-links"><span>watch / update</span><i/><ArrowDown/></div><div className="worker-nodes">{["Node A","Node B","Node C"].map((n,i)=><section key={n}><header><Server/><b>{n}</b></header><span><Activity/>kubelet</span><span><Boxes/>runtime</span><div className="node-pods">{Array.from({length:i===1?2:3}).map((_,j)=><i key={j}/>)}</div></section>)}</div></div>; }
function Slide20() { return <DiagramSlide number={20} title="O cluster separa decisão e execução" section="kubernetes" bullets={[<>O control plane mantém a visão global e toma decisões. Os Nodes executam Pods por meio do kubelet, do runtime e da implementação de rede.</>,<>Componentes não coordenam o cluster por conexões ad hoc: registram e observam objetos na API. O API Server funciona como fronteira consistente de validação, autorização e persistência.</>]}><ClusterArchitecture/></DiagramSlide>; }

function ApiEtcdVisual() { return <div className="visual-panel api-etcd"><header><Braces/><div><b>API Server</b><small>autenticação · autorização · admission · validação</small></div></header><div className="request-line"><UserRound/><ArrowRight/><span>PATCH Deployment</span><ArrowRight/><Braces/></div><ArrowDown/><div className="etcd-cluster"><section><Database/><b>etcd 1</b><small>leader</small></section><section><Database/><b>etcd 2</b><small>follower</small></section><section><Database/><b>etcd 3</b><small>follower</small></section></div><p><ShieldCheck/>Uma mudança só se torna estado do cluster depois de persistida conforme o protocolo do etcd.</p></div>; }
function Slide21() { return <TextSlide number={21} title="API Server e etcd sustentam o estado do cluster" section="kubernetes" bullets={[<>O API Server valida objetos, aplica autenticação, autorização e admission, e expõe operações de leitura, watch e escrita. É o ponto de encontro dos demais componentes.</>,<>etcd mantém o estado persistente do cluster como um log replicado. Perder todos os Pods de aplicação é recuperável se a API e os dados existirem; perder o estado do control plane compromete a capacidade de reconstrução.</>,<>Por isso, o próprio control plane precisa de alta disponibilidade, quorum e backups testados. Kubernetes automatiza workloads, mas também é um sistema distribuído que precisa ser operado.</>]} visual={<ApiEtcdVisual/>}/>; }

function ControllerVisual() { const targets=[[Boxes,"Deployment controller","ReplicaSets"],[Server,"Node controller","condições e evictions"],[Network,"EndpointSlice controller","backends de Services"],[HardDrive,"PV controller","volumes e claims"]] as Array<[LucideIcon,string,string]>; return <div className="visual-panel controller-fanout"><header><RefreshCcw/><b>Control loops especializados</b></header>{targets.map(([Icon,title,target])=><section key={title}><Icon/><div><b>{title}</b><small>reconcilia {target}</small></div><span>watch → compare → act</span></section>)}</div>; }
function Slide22() { return <TextSlide number={22} title="Controllers transformam observação em ação" section="kubernetes" bullets={[<>Controllers fazem watch de tipos de objeto e reagem a mudanças. Cada loop compara `spec` e `status`, executa uma operação idempotente e registra o novo estado.</>,<>A ação pode ser criar outro objeto, atualizar um status ou chamar uma API externa. Repetir a reconciliação não deve produzir efeitos indevidos; falhas temporárias são tratadas com novas tentativas.</>,<>Operators estendem o mesmo padrão para domínios específicos, codificando conhecimento operacional — por exemplo, como promover uma réplica ou executar um upgrade seguro.</>]} visual={<ControllerVisual/>}/>; }

function SchedulerVisual({step}:{step:number}) { const nodes=[{n:"Node A",cpu:"2 livres",mem:"4 GiB",ok:false,why:"memória insuficiente"},{n:"Node B",cpu:"8 livres",mem:"24 GiB",ok:true,why:"score 86"},{n:"Node C",cpu:"6 livres",mem:"32 GiB",ok:true,why:"score 72"}]; return <div className="scheduler-visual"><div className="pending-pod"><Container/><b>Pod pendente</b><code>4 CPU · 16 GiB</code></div><FlowArrow label="filter"/><div className="candidate-nodes">{nodes.map((x,i)=><section key={x.n} className={step>=1&&!x.ok?"rejected":step>=2&&i===1?"selected":""}><Server/><b>{x.n}</b><span>{x.cpu}</span><span>{x.mem}</span>{step>=1&&<small>{x.ok?<Check/>:<X/>}{x.why}</small>}</section>)}</div><Reveal at={2} step={step} className="binding-result"><Scale/><span><b>Binding:</b> Pod → Node B</span></Reveal></div>; }
function Slide23({step}:SlideProps) { return <DiagramSlide number={23} title="Scheduler filtra e pontua Nodes" section="kubernetes" bullets={[<>Filtering elimina Nodes que não satisfazem requisitos rígidos: recursos, volumes, afinidade obrigatória, taints e restrições de portas.</>,<>Scoring compara os candidatos restantes segundo plugins e pesos. O resultado é uma decisão de placement, não a inicialização do processo; o kubelet executa essa parte.</>]} note={<><b>Importante</b><span>O scheduler usa requests declarados, não uma previsão perfeita do consumo real.</span></>}><SchedulerVisual step={step}/></DiagramSlide>; }

function RequestsLimitsVisual() { return <div className="visual-panel requests-limits"><header><Gauge/><b>Do manifesto ao kernel</b></header><section><div><b>request</b><code>cpu: 500m</code><code>memory: 512Mi</code></div><ArrowRight/><span><Scale/>scheduler reserva capacidade</span></section><section><div><b>limit</b><code>cpu: 1</code><code>memory: 1Gi</code></div><ArrowRight/><span><Shield/>cgroups impõem teto</span></section><div className="resource-outcomes"><span><Cpu/><b>CPU</b><small>throttling</small></span><span><MemoryStick/><b>Memória</b><small>OOM kill</small></span></div></div>; }
function Slide24() { return <TextSlide number={24} title="Requests e limits mudam placement e execução" section="kubernetes" bullets={[<>Requests representam a capacidade usada pelo scheduler para admitir e posicionar o Pod. Se forem baixos demais, muitos Pods cabem no papel e competem na prática; se forem altos demais, Nodes parecem cheios.</>,<>Limits são aplicados em runtime por cgroups. CPU acima do limite sofre throttling; memória acima do limite pode resultar em OOM kill, pois memória não pode ser simplesmente atrasada como tempo de CPU.</>,<>Qualidade de serviço, prioridade e pressão do Node influenciam eviction. “O cluster possui memória livre” não garante que um processo específico sobreviverá a um pico mal dimensionado.</>]} visual={<RequestsLimitsVisual/>}/>; }

function TopologyVisual() { return <div className="visual-panel topology-placement"><header><Cloud/><b>Região</b><small>3 zonas · 3 failure domains</small></header><div>{["AZ A","AZ B","AZ C"].map((az,i)=><section key={az}><b>{az}</b><Server/><div>{i===0?<><span/><span className="bad"/><span className="bad"/></>:<span/>}</div><small>{i===0?"sem spread: risco concentrado":"1 réplica"}</small></section>)}</div><p><ShieldCheck/>anti-affinity e topology spread transformam topologia em requisito de placement.</p></div>; }
function Slide25() { return <TextSlide number={25} title="Placement deve refletir failure domains" section="kubernetes" bullets={[<>Três réplicas no mesmo Node continuam formando um único ponto de falha. Alta disponibilidade exige distribuir Pods por Nodes, racks ou zonas que não falhem juntos.</>,<>Node affinity seleciona topologias desejadas; pod anti-affinity evita co-localização; taints reservam Nodes; topology spread constraints controlam o desbalanceamento entre domínios.</>,<>Regras rígidas demais podem tornar Pods impossíveis de agendar durante uma falha. A política deve equilibrar distribuição, capacidade excedente e comportamento degradado.</>]} visual={<TopologyVisual/>}/>; }

function NodeFailureVisual({step}:{step:number}) { return <div className="node-failure"><div className="failure-cluster">{["Node A","Node B","Node C"].map((n,i)=><section key={n} className={step>=1&&i===1?"dead":""}><Server/><b>{n}</b><div>{Array.from({length:i===1?2:1}).map((_,j)=><span key={j}><Container/>Pod</span>)}</div>{step>=1&&i===1&&<CircleX/>}</section>)}</div><Reveal at={1} step={step} className="failure-observation"><Activity/><span>Node B deixa de renovar heartbeat; sua condição torna-se indisponível.</span></Reveal><Reveal at={2} step={step} className="failure-recovery"><RefreshCcw/><span>Controllers substituem Pods; scheduler os posiciona em Nodes com capacidade.</span></Reveal></div>; }
function Slide26({step}:SlideProps) { return <DiagramSlide number={26} title="Self-healing é uma cadeia de decisões" section="kubernetes" bullets={[<>A perda de um Node não “move” processos existentes. O control plane detecta indisponibilidade, invalida endpoints e cria novas instâncias a partir do estado desejado.</>,<>Recuperação depende de capacidade livre, imagem acessível, volumes montáveis, readiness correta e aplicações capazes de reiniciar. Kubernetes coordena; não elimina essas dependências.</>]} note={<><b>RTO real</b><span>detecção + decisão + pull da imagem + startup + readiness.</span></>}><NodeFailureVisual step={step}/></DiagramSlide>; }

function LimitsTable() { const rows=[["Pod morreu","Controller cria outro","estado em memória pode sumir"],["Node morreu","Pods são recriados","capacidade e volumes precisam existir"],["AZ morreu","placement pode sobreviver","cluster e dependências devem ser multi-AZ"],["Dado foi corrompido","nenhuma correção automática","replicação pode propagar o erro"]]; return <div className="visual-panel limits-table"><header><span>Evento</span><span>O que Kubernetes faz</span><span>O que permanece seu problema</span></header>{rows.map(r=><div key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><small>{r[2]}</small></div>)}</div>; }
function Slide27() { return <TextSlide number={27} title="Kubernetes não torna a aplicação disponível sozinho" section="kubernetes" bullets={[<>O orquestrador repõe processos e atualiza roteamento, mas não conhece a semântica do seu estado. Recriar um banco vazio satisfaria “um Pod executando” e ainda assim destruiria o serviço.</>,<>Readiness mal definida envia tráfego cedo demais; liveness agressiva cria loops de reinício; réplicas sem distribuição compartilham a mesma falha. Automação amplifica tanto boas políticas quanto políticas ruins.</>,<>A disponibilidade final é o produto de compute, rede, storage, dados e operação. Agora precisamos seguir o tráfego e entender como endpoints efêmeros permanecem acessíveis.</>]} visual={<LimitsTable/>}/>; }

function PodNetworkVisual() { return <div className="visual-panel pod-network"><header><Container/><div><b>Pod</b><small>um network namespace compartilhado</small></div></header><div className="pod-containers"><span><Box/><b>app</b><small>:8080</small></span><span><Box/><b>sidecar</b><small>:15000</small></span></div><div className="localhost-link"><Cable/><span>comunicação por localhost</span></div><div className="pod-interface"><Network/><b>eth0 · 10.42.1.18</b><span>veth → rede do Node → CNI</span></div></div>; }
function Slide28() { return <TextSlide number={28} title="Um Pod possui identidade de rede própria" section="rede" bullets={[<>Todos os containers de um Pod compartilham o mesmo network namespace e se comunicam por `localhost`. O Pod recebe um IP próprio e suas portas pertencem à unidade, não a cada container.</>,<>A implementação de rede conecta esse namespace ao Node e ao restante do cluster, normalmente por um plugin CNI. Roteamento, encapsulamento ou programação do fabric variam por implementação.</>,<>O IP do Pod é efêmero: ao ser recriado em outro Node, ele pode mudar. Aplicações não devem usar esse endereço como identidade durável.</>]} visual={<PodNetworkVisual/>}/>; }

function ServiceVisual() { return <div className="visual-panel service-visual"><div className="service-name"><Network/><b>Service · api</b><code>10.96.0.20:80</code><small>DNS: api.default.svc</small></div><FlowArrow label="seleção por labels"/><div className="endpoint-row"><span><Container/>10.42.1.18</span><span className="removed"><Container/>10.42.2.9</span><span><Container/>10.42.3.24</span></div><div className="endpoint-update"><RefreshCcw/><span>EndpointSlice remove o Pod antigo e adiciona o substituto sem mudar o nome do Service.</span></div></div>; }
function Slide29() { return <TextSlide number={29} title="Service desacopla nome e IP dos Pods" section="rede" bullets={[<>Um Service seleciona Pods por labels e oferece um endpoint virtual estável. DNS resolve o nome do serviço; o data plane direciona cada conexão para um backend saudável.</>,<>EndpointSlices registram os endereços atuais. Quando um Pod falha ou perde readiness, ele sai do conjunto; quando o substituto fica pronto, entra com outro IP.</>,<>O Service estabiliza descoberta, não sessões ou estado. Conexões existentes podem cair, retries precisam ser limitados e operações devem considerar idempotência.</>]} visual={<ServiceVisual/>}/>; }

function RequestPathVisual({step}:{step:number}) { const items=[[Globe2,"Cliente","HTTPS"],[Cloud,"Load balancer","L4 ou L7"],[Route,"Gateway / Ingress","host, path, TLS"],[Network,"Service","endpoint virtual"],[Container,"Pod","processo :8080"]] as Array<[LucideIcon,string,string]>; return <div className="request-path">{items.map(([Icon,title,detail],i)=><Reveal key={title} at={Math.min(i,2)} step={step} className="path-hop"><section><span>{i+1}</span><Icon/><div><b>{title}</b><small>{detail}</small></div></section>{i<items.length-1&&<FlowArrow/>}</Reveal>)}<Reveal at={2} step={step} className="path-return"><Activity/><span>Health e readiness retiram destinos, mas o cliente ainda precisa de timeout e retry.</span></Reveal></div>; }
function Slide30({step}:SlideProps) { return <DiagramSlide number={30} title="Uma requisição atravessa várias fronteiras" section="rede" bullets={[<>North–south é o tráfego entre cliente e cluster; east–west é o tráfego entre serviços internos. Cada salto pode aplicar roteamento, balanceamento, política e observabilidade.</>,<>Load balancer escolhe uma entrada; Gateway ou Ingress interpreta HTTP; Service escolhe um endpoint; a rede do cluster entrega o pacote ao Pod.</>]} note={<><b>Diagnóstico</b><span>“A aplicação não responde” pode significar falha em qualquer etapa desse caminho.</span></>}><RequestPathVisual step={step}/></DiagramSlide>; }

function VpcVisual() { return <div className="visual-panel vpc-visual"><header><Cloud/><b>VPC 10.0.0.0/16</b><small>roteamento isolado por software</small></header><div className="subnet-row"><section><b>Subnet pública</b><span><Router/>Gateway / LB</span><small>0.0.0.0/0 → internet gateway</small></section><section><b>Subnet privada A</b><span><Server/>Nodes</span><small>rota interna + NAT de saída</small></section><section><b>Subnet privada B</b><span><Database/>Dados</span><small>sem rota pública</small></section></div><div className="security-row"><Lock/><span>Security groups e network policies permitem fluxos; rotas apenas definem caminhos.</span></div></div>; }
function Slide31() { return <TextSlide number={31} title="VPC organiza alcance, rotas e políticas" section="rede" bullets={[<>Uma VPC cria um domínio lógico de endereçamento e roteamento. Subnets dividem o espaço por função ou zona; tabelas de rotas determinam o próximo salto para cada destino.</>,<>Ter uma rota não implica permissão. Security groups, firewalls e NetworkPolicies filtram fluxos em camadas diferentes e com capacidades dependentes da implementação.</>,<>NAT permite saída sem expor endereços privados, mas adiciona estado e limites. Load balancers terminam ou encaminham conexões e precisam ser dimensionados como parte do caminho crítico.</>]} visual={<VpcVisual/>}/>; }

function MultiAzCompute() { return <div className="visual-panel multi-az-compute"><div className="regional-entry"><Cloud/><b>Load balancer regional</b><small>health por zona e endpoint</small></div><div className="zone-row">{["AZ A","AZ B","AZ C"].map((az,i)=><section key={az}><header><b>{az}</b><small>failure domain</small></header><span><Server/>2 Nodes</span><div><i/><i/></div><small>{i===1?"capacidade de reserva":"Pods ativos"}</small></section>)}</div><p><ShieldCheck/>A perda de uma zona não deve remover todas as réplicas nem toda a capacidade livre.</p></div>; }
function Slide32() { return <TextSlide number={32} title="Multi-AZ exige distribuição e capacidade excedente" section="rede" bullets={[<>Executar Nodes em três zonas cria failure domains distintos, mas Pods só se beneficiam disso se o scheduler os distribuir por topologia.</>,<>As zonas restantes precisam absorver a carga da zona perdida. Operar a 95% de utilização em condições normais pode tornar o cluster indisponível exatamente durante o failover.</>,<>Dependências também precisam ser regionais ou redundantes: load balancer, control plane, registry, DNS, NAT e storage. Multi-AZ não é uma propriedade isolada do Deployment.</>]} visual={<MultiAzCompute/>}/>; }

function HealthCheckVisual() { return <div className="visual-panel health-check"><header><Activity/><b>Três sinais diferentes</b></header><section><span>1</span><b>Processo vivo</b><small>liveness reinicia travamentos</small></section><section><span>2</span><b>Pronto para tráfego</b><small>readiness controla endpoints</small></section><section><span>3</span><b>Destino alcançável</b><small>load balancer testa o caminho externo</small></section><div className="health-timeline"><i/><span>falha</span><i/><span>detecção</span><i/><span>remoção</span></div><p>O intervalo entre falha e remoção ainda recebe tráfego.</p></div>; }
function Slide33() { return <TextSlide number={33} title="Health checks definem quando parar de enviar tráfego" section="rede" bullets={[<>Liveness responde se o processo deve ser reiniciado; readiness responde se deve receber tráfego. Misturar as duas pode reiniciar uma aplicação apenas porque uma dependência ficou lenta.</>,<>O load balancer possui sua própria visão e intervalo de checagem. Falha, detecção e remoção não são instantâneas; por algum tempo, conexões ainda podem alcançar o destino ruim.</>,<>Checks devem testar o mínimo necessário para o contrato de atendimento. Dependências profundas transformam uma falha parcial em indisponibilidade total por efeito cascata.</>]} visual={<HealthCheckVisual/>}/>; }

function StateBottleneck() { return <div className="visual-panel state-bottleneck"><header><Cloud/><b>Compute multi-AZ</b></header><div className="app-fan"><span><Container/>AZ A</span><span><Container/>AZ B</span><span><Container/>AZ C</span></div><ArrowDown/><div className="single-db"><Database/><b>Banco em AZ A</b><small>única cópia do estado</small><TriangleAlert/></div><p>Três réplicas de aplicação continuam dependentes de um único failure domain.</p></div>; }
function Slide34() { return <TextSlide number={34} title="Compute pode sobreviver e o sistema ainda falhar" section="rede" bullets={[<>Pods stateless podem ser recriados em qualquer zona porque a imagem e a configuração descrevem tudo que precisam. O banco possui informação que não existe no manifesto.</>,<>Se todas as instâncias de aplicação dependem de um banco em uma única AZ, a arquitetura continua single-AZ do ponto de vista do serviço. Escalar compute não replica estado.</>,<>Chegamos ao problema central: <strong>como manter outra cópia do histórico de dados correta o bastante para continuar após uma falha?</strong></>]} visual={<StateBottleneck/>}/>; }

function ReplicationWhy() { return <div className="visual-panel replication-why"><div className="stateless-side"><Container/><b>Aplicação</b><span>imagem + config</span><RefreshCcw/><small>pode ser recriada</small></div><div className="stateful-side"><Database/><b>Banco</b><span>histórico de commits</span><ArrowRight/><Database/><small>precisa de outra cópia</small></div><div className="replication-contract"><ShieldCheck/><span>Topologia + política de ACK definem quais falhas não perdem dados.</span></div></div>; }
function Slide35() { return <TextSlide number={35} title="Replicação preserva o histórico de mudanças" section="replicacao" bullets={[<>Replicar significa manter outra cópia do estado suficientemente atualizada para assumir o serviço ou atender leituras. A cópia precisa estar em outro failure domain para sobreviver à falha-alvo.</>,<>Não existe uma garantia única chamada “replicado”. A política define quando a escrita é confirmada, quanto atraso é aceito e como uma nova autoridade é escolhida.</>,<>O objetivo não é apenas disponibilidade: a promoção deve preservar um histórico válido. Continuar respondendo com dados divergentes pode ser pior que ficar temporariamente indisponível.</>]} visual={<ReplicationWhy/>}/>; }

function ReplicationBackup() { return <div className="visual-panel replication-backup"><section><header><Database/><b>Replicação</b></header><div><span>Primary</span><ArrowRight/><span>Réplica online</span></div><p>Reduz RTO; também replica exclusões e corrupção lógica.</p></section><section><header><HardDrive/><b>Backup</b></header><div><span>Banco</span><ArrowRight/><span>Ponto no tempo T−1</span></div><p>Permite voltar no tempo; exige restore e validação.</p></section><div className="both-note"><ShieldCheck/><b>Alta disponibilidade usa ambos</b><span>réplicas para continuidade, backups para recuperação histórica.</span></div></div>; }
function Slide36() { return <TextSlide number={36} title="Replicação não substitui backup" section="replicacao" bullets={[<>A réplica acompanha mudanças continuamente e pode ser promovida com pouco tempo de indisponibilidade. Como compartilha o histórico lógico, normalmente reproduz `DROP TABLE`, corrupção e ações maliciosas.</>,<>Backup preserva estados anteriores e permite recuperação point-in-time. Ele precisa ser isolado, versionado e testado; uma cópia que nunca foi restaurada é apenas uma suposição.</>,<>Também não basta contar cópias: primary e réplica no mesmo host ou zona continuam expostos à mesma falha física.</>]} visual={<ReplicationBackup/>}/>; }

function WalPrimaryReplica() { return <div className="visual-panel wal-primary"><div className="transaction"><UserRound/><code>UPDATE saldo = saldo - 100</code></div><ArrowDown/><div className="primary-box"><Database/><b>Primary</b><span>ordena commits</span><code>WAL · LSN 842</code></div><FlowArrow label="stream ordenado"/><div className="replica-box"><Database/><b>Réplica</b><span>persiste e reaplica</span><code>replay_lsn 840</code></div><p>O log descreve mudanças; não copia o banco inteiro a cada transação.</p></div>; }
function Slide37() { return <TextSlide number={37} title="Primary e réplicas compartilham um log ordenado" section="replicacao" bullets={[<>No modelo primary–replica, o primary aceita e ordena escritas. Antes de confirmar o commit local, registra no WAL informação suficiente para refazer a mudança após uma queda.</>,<>Cada posição do log recebe um identificador monotônico, aqui chamado LSN. Réplicas consomem a mesma ordem, persistem os registros e aplicam as mudanças localmente.</>,<>Leituras em réplica podem observar um estado anterior. Replicação física, lógica, multi-leader e leaderless usam mecanismos diferentes; este fluxo fornece a base para discutir durabilidade e failover.</>]} visual={<WalPrimaryReplica/>}/>; }

function LsnPipeline({step}:{step:number}) { const stages=[[Network,"Recebido","write_lsn = 842","chegou ao processo"],[HardDrive,"Durável","flush_lsn = 840","fsync concluído"],[Database,"Aplicado","replay_lsn = 838","visível para leitura"]] as Array<[LucideIcon,string,string,string]>; return <div className="lsn-pipeline-diagram"><div className="commit-source"><Database/><b>Primary</b><code>commit_lsn = 842</code></div><FlowArrow label="stream de WAL"/><div className="lsn-stages">{stages.map(([Icon,title,lsn,detail],i)=><section key={title} className={step>=i?"active":"muted"}><span>{i+1}</span><Icon/><b>{title}</b><code>{lsn}</code><small>{detail}</small></section>)}</div><Reveal at={2} step={step} className="lag-breakdown"><span><b>2</b> registros sem flush remoto</span><span><b>2</b> registros duráveis aguardando replay</span></Reveal></div>; }
function Slide38({step}:SlideProps) { return <DiagramSlide number={38} title="Receber, persistir e aplicar são etapas distintas" section="replicacao" bullets={[<>Uma réplica pode ter recebido o registro em memória sem torná-lo durável; pode tê-lo em disco sem que leituras já enxerguem a mudança.</>,<>Por isso, “a réplica está atualizada” só tem significado quando se define a posição observada: write, flush ou replay.</>]} note={<><b>Contrato do ACK</b><span>precisa declarar até qual posição remota a confirmação alcança.</span></>}><LsnPipeline step={step}/></DiagramSlide>; }

type SeqEvent={from:number;to:number;label:string;at:number;tone?:string};
function Sequence({actors,events,step,footer}:{actors:string[];events:SeqEvent[];step:number;footer:string}) { return <div className="sequence"><div className="sequence-actors">{actors.map(a=><span key={a}><CircleDot/><b>{a}</b></span>)}</div><div className="sequence-body">{actors.map((a,i)=><i key={a} style={{left:`${((i+.5)/actors.length)*100}%`}}/>)}{events.map((e,i)=>{const left=((Math.min(e.from,e.to)+.5)/actors.length)*100;const right=100-(((Math.max(e.from,e.to)+.5)/actors.length)*100);return <Reveal key={`${i}-${e.label}`} at={e.at} step={step} className="sequence-event"><div className={`sequence-line ${e.to<e.from?"reverse":""} ${e.tone||""}`} style={{left:`${left}%`,right:`${right}%`,top:`${5+i*12}%`}}><span>{i+1}</span><b>{e.label}</b><u/><ArrowRight/></div></Reveal>})}</div><div className="sequence-footer"><Clock3/><span>{footer}</span></div></div>; }
function Slide39({step}:SlideProps) { const events=[{from:0,to:1,label:"COMMIT",at:0},{from:1,to:1,label:"WAL local + fsync",at:0},{from:1,to:2,label:"envia LSN 842",at:1},{from:2,to:2,label:"remote flush",at:1},{from:2,to:1,label:"ACK durável",at:2,tone:"success"},{from:1,to:0,label:"HTTP 201",at:2,tone:"success"}]; return <DiagramSlide number={39} title="Replicação síncrona inclui a réplica no commit" section="replicacao" bullets={[<>O primary só confirma quando a condição remota configurada é satisfeita. Para sobreviver à perda do primary, o critério relevante é normalmente remote flush.</>,<>A escrita ganha durabilidade em outro failure domain, mas seu caminho crítico incorpora rede e fsync remoto. Uma réplica lenta pode aumentar latência ou indisponibilidade.</>]}><Sequence actors={["Cliente","Primary","Réplica"]} events={events} step={step} footer="Após o HTTP 201, o LSN existe de forma durável no primary e na réplica participante."/></DiagramSlide>; }

function Slide40({step}:SlideProps) { const events=[{from:0,to:1,label:"COMMIT",at:0},{from:1,to:1,label:"WAL local + fsync",at:0},{from:1,to:0,label:"HTTP 201",at:0,tone:"danger"},{from:1,to:2,label:"envia LSN 842",at:1},{from:2,to:2,label:"remote flush",at:2}]; return <DiagramSlide number={40} title="Replicação assíncrona retira a rede do ACK" section="replicacao" bullets={[<>O cliente recebe sucesso depois da persistência local. Envio e flush remoto ocorrem fora do caminho crítico, reduzindo latência de escrita.</>,<>Durante o replication lag, uma escrita confirmada pode existir apenas no primary. Se ele for perdido antes do remote flush, promover a réplica implica perda de dados.</>]} note={<><b>Pergunta</b><span>Se a falha ocorrer depois do HTTP 201 e antes do evento 5, o que o sucesso realmente garantiu?</span></>}><Sequence actors={["Cliente","Primary","Réplica"]} events={events} step={step} footer="Menor latência local; RPO maior que zero enquanto o WAL confirmado ainda não ficou durável remotamente."/></DiagramSlide>; }

function LagFailoverVisual() { return <div className="visual-panel lag-failover"><header><Clock3/><b>Estado imediatamente antes da falha</b></header><div className="lsn-scale"><span>839</span><span>840</span><span>841</span><span>842</span></div><div className="lsn-bars"><section><b>Primary</b><i/><i/><i/><i/></section><section><b>Réplica</b><i/><i className="missing"/><i className="missing"/><i className="missing"/></section></div><div className="promotion"><CircleX/><span>Primary perdido</span><ArrowRight/><Database/><span>Réplica promovida</span></div><div className="loss-note"><TriangleAlert/><b>RPO observado: 3 registros</b><span>LSNs 840–842 foram confirmados, mas não existem no novo primary.</span></div></div>; }
function Slide41() { return <TextSlide number={41} title="Replication lag transforma-se em RPO no failover" section="replicacao" bullets={[<>Lag pode existir no transporte, no flush ou no replay. Para escolher um candidato a promoção, o ponto crítico é o último LSN durável, não apenas quantos segundos a monitoração exibe.</>,<>Failover precisa identificar a cópia mais avançada e impedir o primary antigo de voltar a escrever. Fencing, leases ou quorum evitam dois primaries ativos — o split brain.</>,<>RPO é a perda de dados aceitável; o valor observado corresponde à diferença entre o último commit confirmado e o histórico durável promovido.</>]} visual={<LagFailoverVisual/>}/>; }

function QuorumAzVisual({step}:{step:number}) { return <div className="quorum-az"><div className="quorum-zones">{["AZ A","AZ B","AZ C"].map((az,i)=><section key={az} className={step>=2&&i===1?"failed":""}><Cloud/><b>{az}</b><Database/><span>{i===0?"Leader":"Follower"}</span><small>{i===0?"aceita escrita":"replica WAL"}</small></section>)}</div><Reveal at={1} step={step} className="quorum-commit"><span>Leader</span><ArrowRight/><b>WAL + fsync</b><ArrowRight/><span>1 follower</span><strong><Check/>2/3 → commit</strong></Reveal><Reveal at={2} step={step} className="quorum-survival"><TriangleAlert/><span>AZ B perdida</span><ArrowRight/><b>A + C ainda formam maioria</b></Reveal></div>; }
function Slide42({step}:SlideProps) { return <DiagramSlide number={42} title="Quorum permite tolerar uma falha de zona" section="replicacao" bullets={[<>Com três membros em três AZs, uma maioria de dois pode confirmar o log e eleger autoridade. Não é necessário esperar o membro mais lento.</>,<>Perder uma AZ mantém dois votos, desde que a rede e a capacidade restantes estejam saudáveis. A latência entre zonas passa a integrar o commit.</>]} note={<><b>Regra operacional</b><span>membros e failure domains devem ser planejados juntos; três nós em duas zonas não oferecem a mesma independência.</span></>}><QuorumAzVisual step={step}/></DiagramSlide>; }

function GeographyVisual() { return <div className="visual-panel geography"><section><RadioTower/><b>São Paulo</b><small>commit local · 4 ms</small></section><div className="fiber-link"><span>≈ 7.500 km</span><i/><ArrowRight/><b>RTT ilustrativo: 110 ms</b></div><section><RadioTower/><b>Virginia</b><small>cópia remota</small></section><div className="physics-note"><Clock3/><span>Confirmação síncrona inter-regional precisa esperar pelo menos o percurso de rede e processamento remoto.</span></div></div>; }
function Slide43() { return <TextSlide number={43} title="Geografia entra no caminho crítico" section="distribuidos" bullets={[<>Dentro de uma região, zonas são conectadas para baixa latência; entre regiões, distância física impõe dezenas ou centenas de milissegundos de RTT.</>,<>Se a região remota participa do commit, cada escrita herda esse custo. Paralelismo pode esconder trabalho, mas não elimina o tempo necessário para a informação atravessar a rede.</>,<>Por isso, muitas arquiteturas usam commit síncrono multi-AZ e replicação assíncrona inter-regional: RPO zero para falha de AZ, mas RPO maior que zero para desastre regional.</>]} visual={<GeographyVisual/>}/>; }

function ActiveModesVisual() { return <div className="visual-panel active-modes"><section><header><ShieldCheck/><b>Active–passive</b></header><div><span>Região A · ativa</span><ArrowRight/><span>Região B · standby</span></div><p>Escrita tem uma autoridade; failover muda roteamento e promove dados.</p></section><section><header><Split/><b>Active–active</b></header><div><span>Região A · escreve</span><ArrowRight/><span>Região B · escreve</span></div><p>Menor latência local, mas conflitos e ordenação tornam-se parte do modelo de dados.</p></section></div>; }
function Slide44() { return <TextSlide number={44} title="Active–passive e active–active resolvem problemas diferentes" section="distribuidos" bullets={[<>Em active–passive, uma região recebe escritas e outra mantém uma cópia. O desenho simplifica autoridade, mas failover exige promover dados, atualizar roteamento e validar que a região antiga não continuará ativa.</>,<>Em active–active, ambas atendem tráfego e podem aceitar escritas. O compute é fácil de duplicar; o estado precisa lidar com concorrência, conflitos, IDs globais e leituras em diferentes posições.</>,<>Active–active só vale a complexidade quando o requisito de latência ou disponibilidade regional justifica mudar a semântica da aplicação.</>]} visual={<ActiveModesVisual/>}/>; }

function ConsistencyVisual() { return <div className="visual-panel consistency"><header><Clock3/><b>WRITE X = 20 em São Paulo</b></header><div className="consistency-times"><section><b>t0</b><span>SP: 10</span><span>US: 10</span></section><section><b>t1</b><span className="fresh">SP: 20</span><span className="stale">US: 10</span></section><section><b>t2</b><span className="fresh">SP: 20</span><span className="fresh">US: 20</span></section></div><div className="consistency-contracts"><span><ShieldCheck/><b>Strong</b><small>leitura posterior não retorna estado anterior</small></span><span><RefreshCcw/><b>Eventual</b><small>réplicas convergem depois</small></span></div></div>; }
function Slide45() { return <TextSlide number={45} title="Consistência define o que uma leitura pode observar" section="distribuidos" bullets={[<>Strong consistency exige que operações confirmadas pareçam seguir uma única ordem válida. Uma leitura posterior não pode retornar um valor anterior à escrita confirmada.</>,<>Eventual consistency permite divergência temporária entre réplicas, desde que elas convirjam quando novas atualizações cessarem. A aplicação precisa tolerar leitura stale e possíveis conflitos.</>,<>Entre esses extremos existem contratos úteis, como read-your-writes e monotonic reads. Escolher consistência é definir semântica percebida pelo usuário, não apenas configurar o banco.</>]} visual={<ConsistencyVisual/>}/>; }

function RaftVisual({step}:{step:number}) { return <div className="raft"><div className="raft-nodes">{["A","B","C"].map((n,i)=><section key={n} className={step>=2&&i===0?"failed":step>=3&&i===1?"leader":""}><Database/><b>Nó {n}</b><span>{i===0&&step<2?"Leader":i===1&&step>=3?"Novo leader":"Follower"}</span></section>)}</div><Reveal at={1} step={step} className="raft-log"><span>Leader recebe entrada</span><ArrowRight/><b>replica log</b><ArrowRight/><span>maioria confirma</span></Reveal><Reveal at={2} step={step} className="raft-failure"><CircleX/><span>Leader A falha</span></Reveal><Reveal at={3} step={step} className="raft-election"><GitBranch/><span>B e C elegem B; apenas histórico comprometido pode continuar.</span></Reveal></div>; }
function Slide46({step}:SlideProps) { return <DiagramSlide number={46} title="Consensus escolhe uma autoridade e um histórico" section="distribuidos" bullets={[<>Raft organiza consenso em eleição de leader, replicação de log e regras de segurança. Uma entrada torna-se committed depois de reconhecida por maioria sob as condições do protocolo.</>,<>Quando o leader falha, os membros elegem outro com histórico compatível. O objetivo não é apenas escolher alguém: é impedir que entradas conflitantes sejam tratadas como comprometidas.</>]} note={<><b>Conexão</b><span>etcd usa Raft; o mesmo tipo de problema aparece no control plane e em bancos distribuídos.</span></>}><RaftVisual step={step}/></DiagramSlide>; }

function CapVisual() { return <div className="visual-panel cap"><div className="partition-regions"><section><RadioTower/><b>Região A</b><code>saldo = 100</code><span>WRITE 80?</span></section><div><Unplug/><b>PARTIÇÃO</b><small>mensagens não chegam</small></div><section><RadioTower/><b>Região B</b><code>saldo = 100</code><span>WRITE 50?</span></section></div><div className="cap-choices"><span><ShieldCheck/><b>Preservar consistência</b><small>um lado recusa operações</small></span><span><Zap/><b>Preservar disponibilidade</b><small>ambos aceitam; divergência precisa ser resolvida</small></span></div></div>; }
function Slide47() { return <TextSlide number={47} title="CAP importa quando a rede particiona" section="distribuidos" bullets={[<>Durante uma partição, dois grupos não conseguem coordenar. Se ambos aceitarem operações conflitantes, disponibilidade é preservada, mas a visão imediatamente consistente deixa de ser possível.</>,<>Se o sistema exige uma única ordem, pelo menos um lado precisa recusar ou atrasar operações até recuperar coordenação. Isso sacrifica disponibilidade naquele intervalo.</>,<>“Escolha dois de três” esconde o contexto: partition tolerance é uma condição do ambiente; a decisão prática é qual comportamento oferecer <strong>durante a partição e por operação</strong>.</>]} visual={<CapVisual/>}/>; }

function RpoRtoMatrix() { return <div className="visual-panel rpo-rto"><header><Scale/><b>Objetivos → arquitetura provável</b></header><div className="matrix-head"><span>Topologia</span><span>RPO</span><span>RTO</span><span>Custo/complexidade</span></div>{[["Single-AZ","min–h","min–h","baixo"],["Multi-AZ síncrona","≈ 0","s–min","médio"],["Multi-região passive","s–min","min","alto"],["Multi-região active","depende","s","muito alto"]].map((r,i)=><div key={r[0]} className={i===1?"recommended":""}>{r.map((x,column)=><span key={`${r[0]}-${column}`}>{x}</span>)}</div>)}</div>; }
function Slide48() { return <TextSlide number={48} title="RPO e RTO transformam requisitos em arquitetura" section="distribuidos" bullets={[<><strong>RPO</strong> define quanto estado pode ser perdido; <strong>RTO</strong> define quanto tempo o serviço pode ficar indisponível. Ambos precisam ser mensuráveis e testados.</>,<>RPO zero regional exige confirmação fora da região ou um mecanismo equivalente, adicionando latência e dependência de coordenação remota. RTO baixo exige automação, capacidade pronta e runbooks exercitados.</>,<>Quanto menores RPO e RTO, maior o custo de redundância, observabilidade e testes. O objetivo não é maximizar disponibilidade abstrata, mas satisfazer o contrato do negócio.</>]} visual={<RpoRtoMatrix/>}/>; }

function BreakArchitecture({step}:{step:number}) { const failures=[[Container,"1 · Pod falha","controller substitui"],[Server,"2 · Node falha","scheduler reposiciona"],[Cloud,"3 · AZ falha","outras zonas mantêm quorum"],[Database,"4 · Primary falha","réplica é promovida"],[Globe2,"5 · Região falha","roteamento muda para DR"]] as Array<[LucideIcon,string,string]>; return <div className="break-architecture"><div className="complete-system"><Globe2/><span>Global routing</span><ArrowDown/><Cloud/><span>Região · 3 AZs</span><ArrowDown/><Boxes/><span>Kubernetes</span><ArrowDown/><Database/><span>Banco replicado</span></div><div className="failure-list">{failures.map(([Icon,title,result],i)=><Reveal key={title} at={Math.min(i,4)} step={step}><section><Icon/><b>{title}</b><ArrowRight/><span>{result}</span></section></Reveal>)}</div></div>; }
function Slide49({step}:SlideProps) { return <DiagramSlide number={49} title="Agora podemos quebrar a arquitetura" section="fechamento" bullets={[<>Cada falha é absorvida por um mecanismo diferente. Kubernetes repõe compute; rede remove endpoints; replicação preserva dados; consensus escolhe autoridade.</>,<>A sobrevivência depende de a redundância atravessar o failure domain correto e de existir capacidade suficiente para operar em modo degradado.</>]} note={<><b>Teste final</b><span>A conexão entre regiões caiu, mas ambas continuam saudáveis. Agora o problema não é infraestrutura: é semântica distribuída.</span></>}><BreakArchitecture step={step}/></DiagramSlide>; }

function DecisionSummary() { const rows=[[Server,"Isolamento","VM separa kernels; container separa processos"],[RefreshCcw,"Compute","estado desejado + capacidade + placement"],[Network,"Rede","nome estável + endpoints efêmeros + health"],[Database,"Estado","log replicado + ACK + failover"],[Globe2,"Geografia","latência + consistência + RPO/RTO"]] as Array<[LucideIcon,string,string]>; return <div className="visual-panel decision-summary">{rows.map(([Icon,title,text])=><section key={title}><Icon/><b>{title}</b><span>{text}</span></section>)}</div>; }
function Slide50() { return <TextSlide number={50} title="Cloud é uma composição de contratos" section="fechamento" bullets={[<>Virtualização e containers definem fronteiras de isolamento; Kubernetes define como o compute converge; rede define como tráfego encontra instâncias; replicação define como o estado sobrevive.</>,<>Nenhuma camada remove a física da camada inferior. CPU continua sendo escalonada, pacotes continuam sujeitos a distância e commits continuam dependendo de cópias duráveis.</>,<>Uma arquitetura avançada não é a que usa mais serviços, e sim a que declara suas falhas-alvo e alinha cada mecanismo ao RPO, RTO, latência e custo aceitáveis.</>]} visual={<DecisionSummary/>}/>; }

function QuestionsVisual() { const qs=["Por que três Pods no mesmo Node não representam alta disponibilidade?","O que exatamente um HTTP 201 garante em replicação assíncrona?","Quando active–active é realmente necessário?","Qual falha a sua arquitetura atual não consegue absorver?"]; return <div className="questions-grid">{qs.map((q,i)=><section key={q}><span>{i+1}</span><p>{q}</p></section>)}</div>; }
function Slide51() { return <Slide number={51} title="Perguntas de verificação" section="fechamento" className="questions-slide"><QuestionsVisual/></Slide>; }

function ScenarioQuestionsVisual() { const qs=[
  ["Capacidade", "Cada AZ opera a 70%. Se uma das três zonas falhar, as duas restantes conseguem absorver a carga sem violar requests?"],
  ["Consistência", "Duas regiões active–active perdem comunicação. Quais operações ainda podem ser aceitas sem criar um saldo impossível?"],
  ["Recuperação", "O negócio exige RPO regional zero e RTO de 60 segundos. Qual componente participa do ACK e como o failover é testado?"],
  ["Diagnóstico", "O Pod está Ready, mas usuários recebem timeout. Em qual ordem você investiga Service, Gateway, load balancer e aplicação?"],
]; return <div className="scenario-question-grid">{qs.map(([label,q],i)=><section key={label}><span>{i+1}</span><div><b>{label}</b><p>{q}</p></div></section>)}</div>; }
function Slide52() { return <Slide number={52} title="Cenários para discussão" section="fechamento" className="scenario-questions-slide"><ScenarioQuestionsVisual/><div className="sources-note"><b>Leituras técnicas usadas no roteiro</b><span>Documentação oficial do Linux, OCI e Kubernetes; artigo original do Raft; Gilbert & Lynch sobre CAP.</span></div></Slide>; }

export const slides: SlideDefinition[] = [
  {title:"Cloud por baixo das abstrações",duration:"1 min",maxStep:0,section:"fundamentos",component:Slide01},
  {title:"Mapa · Fundamentos",duration:"transição",maxStep:0,section:"fundamentos",component:TopicFundamentos},
  {title:"Aplicação em uma VM",duration:"1,5 min",maxStep:0,section:"fundamentos",component:Slide02},{title:"Infraestrutura compartilhada",duration:"1,5 min",maxStep:0,section:"fundamentos",component:Slide03},{title:"Failure domains",duration:"1,5 min",maxStep:0,section:"fundamentos",component:Slide04},{title:"Cinco etapas",duration:"1 min",maxStep:0,section:"fundamentos",component:Slide05},
  {title:"Mapa · Virtualização",duration:"transição",maxStep:0,section:"virtualizacao",component:TopicVirtualizacao},
  {title:"Por que virtualizar",duration:"1,5 min",maxStep:0,section:"virtualizacao",component:Slide06},{title:"Hypervisor",duration:"1,5 min",maxStep:0,section:"virtualizacao",component:Slide07},{title:"Virtualização de CPU",duration:"2 min",maxStep:2,section:"virtualizacao",component:Slide08},{title:"Memória e I/O",duration:"1,5 min",maxStep:0,section:"virtualizacao",component:Slide09},{title:"VMs e containers",duration:"1,5 min",maxStep:0,section:"virtualizacao",component:Slide10},
  {title:"Mapa · Containers",duration:"transição",maxStep:0,section:"containers",component:TopicContainers},
  {title:"Container é processo",duration:"1,5 min",maxStep:0,section:"containers",component:Slide11},{title:"Namespaces",duration:"2 min",maxStep:0,section:"containers",component:Slide12},{title:"cgroups",duration:"2 min",maxStep:0,section:"containers",component:Slide13},{title:"Imagens e layers",duration:"1,5 min",maxStep:0,section:"containers",component:Slide14},{title:"Container runtime",duration:"1,5 min",maxStep:0,section:"containers",component:Slide15},{title:"Limite de um host",duration:"1 min",maxStep:0,section:"containers",component:Slide16},
  {title:"Mapa · Orquestração",duration:"transição",maxStep:0,section:"kubernetes",component:TopicKubernetes},
  {title:"Por que orquestrar",duration:"1,5 min",maxStep:0,section:"kubernetes",component:Slide17},{title:"Reconciliação",duration:"2 min",maxStep:2,section:"kubernetes",component:Slide18},{title:"Cadeia de objetos",duration:"1,5 min",maxStep:0,section:"kubernetes",component:Slide19},{title:"Arquitetura do cluster",duration:"2 min",maxStep:0,section:"kubernetes",component:Slide20},{title:"API Server e etcd",duration:"1,5 min",maxStep:0,section:"kubernetes",component:Slide21},{title:"Controllers",duration:"1 min",maxStep:0,section:"kubernetes",component:Slide22},{title:"Scheduler",duration:"2 min",maxStep:2,section:"kubernetes",component:Slide23},{title:"Requests e limits",duration:"1,5 min",maxStep:0,section:"kubernetes",component:Slide24},{title:"Placement e topologia",duration:"1,5 min",maxStep:0,section:"kubernetes",component:Slide25},{title:"Falha de Node",duration:"1,5 min",maxStep:2,section:"kubernetes",component:Slide26},{title:"Limites do Kubernetes",duration:"1 min",maxStep:0,section:"kubernetes",component:Slide27},
  {title:"Mapa · Rede e multi-AZ",duration:"transição",maxStep:0,section:"rede",component:TopicRede},
  {title:"Rede do Pod",duration:"1,5 min",maxStep:0,section:"rede",component:Slide28},{title:"Service",duration:"1,5 min",maxStep:0,section:"rede",component:Slide29},{title:"Caminho da requisição",duration:"2 min",maxStep:2,section:"rede",component:Slide30},{title:"VPC",duration:"1,5 min",maxStep:0,section:"rede",component:Slide31},{title:"Compute multi-AZ",duration:"1,5 min",maxStep:0,section:"rede",component:Slide32},{title:"Health checks",duration:"1 min",maxStep:0,section:"rede",component:Slide33},{title:"O problema do estado",duration:"1 min",maxStep:0,section:"rede",component:Slide34},
  {title:"Mapa · Replicação",duration:"transição",maxStep:0,section:"replicacao",component:TopicReplicacao},
  {title:"Por que replicar",duration:"1,5 min",maxStep:0,section:"replicacao",component:Slide35},{title:"Replicação e backup",duration:"1 min",maxStep:0,section:"replicacao",component:Slide36},{title:"Primary, réplica e WAL",duration:"1,5 min",maxStep:0,section:"replicacao",component:Slide37},{title:"Receber, persistir e aplicar",duration:"2 min",maxStep:2,section:"replicacao",component:Slide38},{title:"Replicação síncrona",duration:"2 min",maxStep:2,section:"replicacao",component:Slide39},{title:"Replicação assíncrona",duration:"2 min",maxStep:2,section:"replicacao",component:Slide40},{title:"Lag e failover",duration:"1,5 min",maxStep:0,section:"replicacao",component:Slide41},{title:"Quorum multi-AZ",duration:"2 min",maxStep:2,section:"replicacao",component:Slide42},
  {title:"Mapa · Multi-região",duration:"transição",maxStep:0,section:"distribuidos",component:TopicDistribuidos},
  {title:"Latência geográfica",duration:"1,5 min",maxStep:0,section:"distribuidos",component:Slide43},{title:"Active–passive e active–active",duration:"1,5 min",maxStep:0,section:"distribuidos",component:Slide44},{title:"Modelos de consistência",duration:"2 min",maxStep:0,section:"distribuidos",component:Slide45},{title:"Consensus e Raft",duration:"3 min",maxStep:3,section:"distribuidos",component:Slide46},{title:"CAP durante partição",duration:"1,5 min",maxStep:0,section:"distribuidos",component:Slide47},{title:"RPO e RTO",duration:"2 min",maxStep:0,section:"distribuidos",component:Slide48},
  {title:"Mapa · Síntese",duration:"transição",maxStep:0,section:"fechamento",component:TopicFechamento},
  {title:"Quebrando a arquitetura",duration:"2 min",maxStep:4,section:"fechamento",component:Slide49},{title:"Cloud como contratos",duration:"2 min",maxStep:0,section:"fechamento",component:Slide50},{title:"Perguntas de verificação",duration:"4 min",maxStep:0,section:"fechamento",component:Slide51},{title:"Cenários para discussão",duration:"6 min",maxStep:0,section:"fechamento",component:Slide52},
];
